site_name: Type-safe Redis client for Go
site_url: https://redis.uptrace.dev
repo_url: https://github.com/go-redis/redis
edit_uri: https://github.com/go-redis/docs/edit/master/docs/

nav:
  - 'Redis client for Go':
      - index.md
      - cluster.md
      - sentinel.md
      - ring.md
      - tracing.md
      - changelog.md

  - 'Tutorials':
      - get-all-keys.md
      - rate-limiting.md

extra_css:
  - css/index.css

plugins:
  - search
  - awesome-pages
  - minify:
      minify_html: true

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.sections
    - navigation.expand

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: docs
  - attr_list
